// Generated by https://quicktype.io

export interface EpisodeListRatedResponse {
    page:          number;
    results:       Result[];
    total_pages:   number;
    total_results: number;
}

export interface Result {
    air_date:        string;
    episode_number:  number;
    episode_type:    string;
    id:              number;
    name:            string;
    overview:        string;
    production_code: string;
    runtime:         number;
    season_number:   number;
    show_id:         number;
    still_path:      string;
    vote_average:    number;
    vote_count:      number;
    rating:          number;
}
