// Generated by https://quicktype.io

export interface SerieListFilterGenreResponse {
    page:          number;
    results:       SerieFilterGenre[];
    total_pages:   number;
    total_results: number;
}

export interface SerieFilterGenre {
    backdrop_path:     string;
    first_air_date:    string;
    genre_ids:         number[];
    id:                number;
    name:              string;
    origin_country:    string[];
    original_language: OriginalLanguage;
    original_name:     string;
    overview:          string;
    popularity:        number;
    poster_path:       string;
    vote_average:      number;
    vote_count:        number;
}

export enum OriginalLanguage {
    En = "en",
    Fr = "fr",
    Ja = "ja",
}
